#include "MeshNormalizer.h"
#include <fstream>
#include <iostream>
#include <limits>

// ---------------------------------------------------------
// 1. computeParams
// ---------------------------------------------------------
NormParams MeshNormalizer::computeParams(const std::vector<float>& verts,
                                         float targetSize)
{
    NormParams p;
    p.targetSize = targetSize;
    p.center     = glm::vec3(0.0f);
    p.scale      = 1.0f;

    if (verts.empty()) return p;

    glm::vec3 mn( std::numeric_limits<float>::max());
    glm::vec3 mx(-std::numeric_limits<float>::max());

    for (size_t i = 0; i + 2 < verts.size(); i += 3) {
        glm::vec3 v(verts[i], verts[i+1], verts[i+2]);
        mn = glm::min(mn, v);
        mx = glm::max(mx, v);
    }

    p.center = (mn + mx) * 0.5f;

    glm::vec3 size = mx - mn;
    float maxExtent = std::max({size.x, size.y, size.z});
    p.scale = (maxExtent > 1e-8f) ? (targetSize / maxExtent) : 1.0f;

    std::cout << "[MeshNormalizer] AABB min=("
              << mn.x << "," << mn.y << "," << mn.z << ") max=("
              << mx.x << "," << mx.y << "," << mx.z << ")\n"
              << "  center=(" << p.center.x << "," << p.center.y << "," << p.center.z << ")"
              << "  maxExtent=" << maxExtent
              << "  scale=" << p.scale << std::endl;

    return p;
}

// ---------------------------------------------------------
// 2. applyToVerts
// ---------------------------------------------------------
void MeshNormalizer::applyToVerts(std::vector<float>& verts,
                                  const NormParams& p)
{
    for (size_t i = 0; i + 2 < verts.size(); i += 3) {
        verts[i]   = (verts[i]   - p.center.x) * p.scale;
        verts[i+1] = (verts[i+1] - p.center.y) * p.scale;
        verts[i+2] = (verts[i+2] - p.center.z) * p.scale;
    }
}

// ---------------------------------------------------------
// 3. applyToMeshData
// ---------------------------------------------------------
void MeshNormalizer::applyToMeshData(SoftBodyPhysics::MeshData& md,
                                     const NormParams& p)
{
    applyToVerts(md.verts, p);
    // uvs / tetIds / tetEdgeIds / tetSurfaceTriIds はそのまま
}

// ---------------------------------------------------------
// 4. saveAsObj (verts + indices 版)
// ---------------------------------------------------------
bool MeshNormalizer::saveAsObj(const std::vector<float>& verts,
                               const std::vector<int>&   indices,
                               const std::string&         outPath)
{
    std::ofstream ofs(outPath);
    if (!ofs.is_open()) {
        std::cerr << "[MeshNormalizer] Cannot write OBJ: " << outPath << std::endl;
        return false;
    }

    ofs << "# Generated by MeshNormalizer\n";

    // 頂点
    for (size_t i = 0; i + 2 < verts.size(); i += 3) {
        ofs << "v " << verts[i] << " " << verts[i+1] << " " << verts[i+2] << "\n";
    }

    // 三角形面 (OBJ は 1-origin)
    for (size_t i = 0; i + 2 < indices.size(); i += 3) {
        ofs << "f " << (indices[i]+1)
        << " "  << (indices[i+1]+1)
        << " "  << (indices[i+2]+1) << "\n";
    }

    ofs.close();
    std::cout << "[MeshNormalizer] Saved OBJ: " << outPath
              << "  verts=" << verts.size()/3
              << "  tris="  << indices.size()/3 << std::endl;
    return true;
}

// ---------------------------------------------------------
// 4b. saveAsObj (MeshData 版)
// ---------------------------------------------------------
bool MeshNormalizer::saveAsObj(const SoftBodyPhysics::MeshData& md,
                               const std::string& outPath)
{
    // tetSurfaceTriIds が表面三角形インデックス
    return saveAsObj(md.verts, md.tetSurfaceTriIds, outPath);
}
